### ISSUE TITLE
Possible to install with gnat 4.8.5

### ISSUE THREAD

**Issue by ChthonicOne** [AdaCore/gprbuild#35]
I am trying to do a bootstrap of GPRBuild, but I'm running into issues with gnat 4.8.5 which is what is available for Centos 7.

Initially I get this error:
gpr_build_util.ads:192:11: expression function is an Ada 2012 feature
gpr_build_util.ads:192:11: unit must be compiled with -gnat2012 switch
gpr-compilation.ads:120:39: missing ";"
gnatmake: "/home/foo/gprbuild/sorc/gprbuild-main.adb" compilation error

I then edited your bootstrap.sh to provide the required switch, and got the following error instead:
gprbuild-main.adb:1880:10: "Try_Help" is undefined
gnatmake: "/home/foo/gprbuild/sorc/gprbuild-main.adb" compilation error

Is it going to be possible to make this work with gnat 4.8.5?
If not, is there a way to get a newer version of gnat on Centos 7 than this?

**Comment by landgraf** [comment]
gcc 4.8.5 is too old. See https://github.com/AdaCore/gprbuild/issues/18

**Comment by t-14** [comment]
Correct, 4.8.5 is far too old, you need a recent gcc 6 or 7.

> If not, is there a way to get a newer version of gnat on Centos 7 than this?

We don't support CentOS ourselves, you should check with the community.

**Comment by landgraf** [comment]
> We don't support CentOS ourselves, you should check with the community.
CentOS uses RHEL's sources to build the distribution. So the answer is "use Fedora" :)
